"use client"

import { useEffect, useState } from "react"
import { useRouter } from "next/navigation"
import { Button } from "@/components/ui/button"
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card"
import { Textarea } from "@/components/ui/textarea"
import { Label } from "@/components/ui/label"
import { ArrowLeft, FileText, Upload, Loader2 } from "lucide-react"

export default function TextUploadPage() {
  const [text, setText] = useState("")
  const [isAnalyzing, setIsAnalyzing] = useState(false)
  const router = useRouter()

  useEffect(() => {
    const isAuthenticated = localStorage.getItem("isAuthenticated")
    if (!isAuthenticated) {
      router.push("/")
    }
  }, [router])

  const handleAnalyze = async () => {
    if (!text.trim()) return

    setIsAnalyzing(true)

    // Simulate analysis
    setTimeout(() => {
      // Store text for result page
      localStorage.setItem(
        "analysisData",
        JSON.stringify({
          type: "text",
          content: text,
          timestamp: new Date().toISOString(),
        }),
      )
      router.push("/result")
    }, 2000)
  }

  return (
    <div className="min-h-screen bg-background">
      <div className="p-6 lg:p-8">
        <div className="max-w-4xl mx-auto">
          {/* Header */}
          <div className="flex items-center space-x-4 mb-8">
            <Button variant="ghost" size="sm" onClick={() => router.push("/dashboard")} className="hover:bg-accent/10">
              <ArrowLeft className="h-4 w-4 mr-2" />
              Back to Dashboard
            </Button>
            <div className="flex items-center space-x-2">
              <div className="p-2 bg-blue-50 rounded-lg">
                <FileText className="h-6 w-6 text-blue-600" />
              </div>
              <div>
                <h1 className="text-2xl font-bold text-foreground">Text Analysis</h1>
                <p className="text-muted-foreground">Detect AI-generated text content</p>
              </div>
            </div>
          </div>

          {/* Upload Card */}
          <Card className="border-border">
            <CardHeader>
              <CardTitle className="flex items-center space-x-2">
                <FileText className="h-5 w-5" />
                <span>Text Content Analysis</span>
              </CardTitle>
              <CardDescription>
                Paste or type your text content below to analyze if it was generated by AI
              </CardDescription>
            </CardHeader>
            <CardContent className="space-y-6">
              <div className="space-y-2">
                <Label htmlFor="text-content">Text Content</Label>
                <Textarea
                  id="text-content"
                  placeholder="Paste your text content here..."
                  value={text}
                  onChange={(e) => setText(e.target.value)}
                  className="min-h-[300px] bg-input resize-none"
                />
                <p className="text-sm text-muted-foreground">{text.length} characters</p>
              </div>

              <div className="flex justify-end space-x-4">
                <Button variant="outline" onClick={() => setText("")} disabled={!text.trim() || isAnalyzing}>
                  Clear
                </Button>
                <Button
                  onClick={handleAnalyze}
                  disabled={!text.trim() || isAnalyzing}
                  className="bg-primary hover:bg-primary/90"
                >
                  {isAnalyzing ? (
                    <>
                      <Loader2 className="mr-2 h-4 w-4 animate-spin" />
                      Analyzing...
                    </>
                  ) : (
                    <>
                      <Upload className="mr-2 h-4 w-4" />
                      Analyze Text
                    </>
                  )}
                </Button>
              </div>
            </CardContent>
          </Card>
        </div>
      </div>
    </div>
  )
}
